# Generated by Django 5.0.1 on 2024-01-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouse',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='category',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Mouse',
        ),
    ]
